/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthStudentRouteImport } from './routes/auth.student'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAdminAuditRouteImport } from './routes/app/admin/audit'
import { Route as AppAdminFinanceRouteImport } from './routes/app/admin/finance'
import { Route as AppAdminLogsRouteImport } from './routes/app/admin/logs'
import { Route as AppAdminMonitoringRouteImport } from './routes/app/admin/monitoring'
import { Route as AppAdminPlansRouteImport } from './routes/app/admin/plans'
import { Route as AppAdminReportsRouteImport } from './routes/app/admin/reports'
import { Route as AppAdminSettingsRouteImport } from './routes/app/admin/settings'
import { Route as AppAdminSubscriptionsRouteImport } from './routes/app/admin/subscriptions'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppSchoolIndexRouteImport } from './routes/app/school/index'
import { Route as AppSchoolClassesRouteImport } from './routes/app/school/classes'
import { Route as AppSchoolStudentsRouteImport } from './routes/app/school/students'
import { Route as AppSchoolTeachersRouteImport } from './routes/app/school/teachers'
import { Route as AppSchoolTextsRouteImport } from './routes/app/school/texts'
import { Route as AppStudentIndexRouteImport } from './routes/app/student/index'
import { Route as AppStudentProgressoRouteImport } from './routes/app/student/progresso'
import { Route as AppStudentSimuladosRouteImport } from './routes/app/student/simulados'
import { Route as AppTeacherIndexRouteImport } from './routes/app/teacher/index'
import { Route as AppTeacherResultadosRouteImport } from './routes/app/teacher/resultados'
import { Route as AppTeacherRubricasRouteImport } from './routes/app/teacher/rubricas'
import { Route as AppTeacherTentativasRouteImport } from './routes/app/teacher/tentativas'
import { Route as AppAdminSchoolsIndexRouteImport } from './routes/app/admin/schools/index'
import { Route as AppAdminSchoolsIdRouteImport } from './routes/app/admin/schools/$id'
import { Route as AppSchoolSimuladosIndexRouteImport } from './routes/app/school/simulados.index'
import { Route as AppSchoolSimuladosIdRouteImport } from './routes/app/school/simulados.$id'
import { Route as AppStudentResultadoAttemptIdRouteImport } from './routes/app/student/resultado.$attemptId'
import { Route as AppStudentSimuladoIdRouteImport } from './routes/app/student/simulado.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/auth/student',
  path: '/auth/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminFinanceRoute = AppAdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminMonitoringRoute = AppAdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminPlansRoute = AppAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminSubscriptionsRoute = AppAdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchoolIndexRoute = AppSchoolIndexRouteImport.update({
  id: '/school/',
  path: '/school/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchoolClassesRoute = AppSchoolClassesRouteImport.update({
  id: '/school/classes',
  path: '/school/classes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchoolStudentsRoute = AppSchoolStudentsRouteImport.update({
  id: '/school/students',
  path: '/school/students',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchoolTeachersRoute = AppSchoolTeachersRouteImport.update({
  id: '/school/teachers',
  path: '/school/teachers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchoolTextsRoute = AppSchoolTextsRouteImport.update({
  id: '/school/texts',
  path: '/school/texts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentIndexRoute = AppStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentProgressoRoute = AppStudentProgressoRouteImport.update({
  id: '/student/progresso',
  path: '/student/progresso',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentSimuladosRoute = AppStudentSimuladosRouteImport.update({
  id: '/student/simulados',
  path: '/student/simulados',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeacherIndexRoute = AppTeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeacherResultadosRoute = AppTeacherResultadosRouteImport.update({
  id: '/teacher/resultados',
  path: '/teacher/resultados',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeacherRubricasRoute = AppTeacherRubricasRouteImport.update({
  id: '/teacher/rubricas',
  path: '/teacher/rubricas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeacherTentativasRoute = AppTeacherTentativasRouteImport.update({
  id: '/teacher/tentativas',
  path: '/teacher/tentativas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminSchoolsIndexRoute = AppAdminSchoolsIndexRouteImport.update({
  id: '/admin/schools/',
  path: '/admin/schools/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminSchoolsIdRoute = AppAdminSchoolsIdRouteImport.update({
  id: '/admin/schools/$id',
  path: '/admin/schools/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchoolSimuladosIndexRoute = AppSchoolSimuladosIndexRouteImport.update({
  id: '/school/simulados/',
  path: '/school/simulados/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchoolSimuladosIdRoute = AppSchoolSimuladosIdRouteImport.update({
  id: '/school/simulados/$id',
  path: '/school/simulados/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentResultadoAttemptIdRoute =
  AppStudentResultadoAttemptIdRouteImport.update({
    id: '/student/resultado/$attemptId',
    path: '/student/resultado/$attemptId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppStudentSimuladoIdRoute = AppStudentSimuladoIdRouteImport.update({
  id: '/student/simulado/$id',
  path: '/student/simulado/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/auth/student': typeof AuthStudentRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/finance': typeof AppAdminFinanceRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/monitoring': typeof AppAdminMonitoringRoute
  '/app/admin/plans': typeof AppAdminPlansRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/subscriptions': typeof AppAdminSubscriptionsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/school/classes': typeof AppSchoolClassesRoute
  '/app/school/students': typeof AppSchoolStudentsRoute
  '/app/school/teachers': typeof AppSchoolTeachersRoute
  '/app/school/texts': typeof AppSchoolTextsRoute
  '/app/student/progresso': typeof AppStudentProgressoRoute
  '/app/student/simulados': typeof AppStudentSimuladosRoute
  '/app/teacher/resultados': typeof AppTeacherResultadosRoute
  '/app/teacher/rubricas': typeof AppTeacherRubricasRoute
  '/app/teacher/tentativas': typeof AppTeacherTentativasRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/school/': typeof AppSchoolIndexRoute
  '/app/student/': typeof AppStudentIndexRoute
  '/app/teacher/': typeof AppTeacherIndexRoute
  '/app/admin/schools/$id': typeof AppAdminSchoolsIdRoute
  '/app/school/simulados/$id': typeof AppSchoolSimuladosIdRoute
  '/app/student/resultado/$attemptId': typeof AppStudentResultadoAttemptIdRoute
  '/app/student/simulado/$id': typeof AppStudentSimuladoIdRoute
  '/app/admin/schools/': typeof AppAdminSchoolsIndexRoute
  '/app/school/simulados/': typeof AppSchoolSimuladosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/student': typeof AuthStudentRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/finance': typeof AppAdminFinanceRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/monitoring': typeof AppAdminMonitoringRoute
  '/app/admin/plans': typeof AppAdminPlansRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/subscriptions': typeof AppAdminSubscriptionsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/school/classes': typeof AppSchoolClassesRoute
  '/app/school/students': typeof AppSchoolStudentsRoute
  '/app/school/teachers': typeof AppSchoolTeachersRoute
  '/app/school/texts': typeof AppSchoolTextsRoute
  '/app/student/progresso': typeof AppStudentProgressoRoute
  '/app/student/simulados': typeof AppStudentSimuladosRoute
  '/app/teacher/resultados': typeof AppTeacherResultadosRoute
  '/app/teacher/rubricas': typeof AppTeacherRubricasRoute
  '/app/teacher/tentativas': typeof AppTeacherTentativasRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/school': typeof AppSchoolIndexRoute
  '/app/student': typeof AppStudentIndexRoute
  '/app/teacher': typeof AppTeacherIndexRoute
  '/app/admin/schools/$id': typeof AppAdminSchoolsIdRoute
  '/app/school/simulados/$id': typeof AppSchoolSimuladosIdRoute
  '/app/student/resultado/$attemptId': typeof AppStudentResultadoAttemptIdRoute
  '/app/student/simulado/$id': typeof AppStudentSimuladoIdRoute
  '/app/admin/schools': typeof AppAdminSchoolsIndexRoute
  '/app/school/simulados': typeof AppSchoolSimuladosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/auth/student': typeof AuthStudentRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/finance': typeof AppAdminFinanceRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/monitoring': typeof AppAdminMonitoringRoute
  '/app/admin/plans': typeof AppAdminPlansRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/subscriptions': typeof AppAdminSubscriptionsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/school/classes': typeof AppSchoolClassesRoute
  '/app/school/students': typeof AppSchoolStudentsRoute
  '/app/school/teachers': typeof AppSchoolTeachersRoute
  '/app/school/texts': typeof AppSchoolTextsRoute
  '/app/student/progresso': typeof AppStudentProgressoRoute
  '/app/student/simulados': typeof AppStudentSimuladosRoute
  '/app/teacher/resultados': typeof AppTeacherResultadosRoute
  '/app/teacher/rubricas': typeof AppTeacherRubricasRoute
  '/app/teacher/tentativas': typeof AppTeacherTentativasRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/school/': typeof AppSchoolIndexRoute
  '/app/student/': typeof AppStudentIndexRoute
  '/app/teacher/': typeof AppTeacherIndexRoute
  '/app/admin/schools/$id': typeof AppAdminSchoolsIdRoute
  '/app/school/simulados/$id': typeof AppSchoolSimuladosIdRoute
  '/app/student/resultado/$attemptId': typeof AppStudentResultadoAttemptIdRoute
  '/app/student/simulado/$id': typeof AppStudentSimuladoIdRoute
  '/app/admin/schools/': typeof AppAdminSchoolsIndexRoute
  '/app/school/simulados/': typeof AppSchoolSimuladosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/profile'
    | '/auth/student'
    | '/app/'
    | '/auth/'
    | '/app/admin/audit'
    | '/app/admin/finance'
    | '/app/admin/logs'
    | '/app/admin/monitoring'
    | '/app/admin/plans'
    | '/app/admin/reports'
    | '/app/admin/settings'
    | '/app/admin/subscriptions'
    | '/app/admin/users'
    | '/app/school/classes'
    | '/app/school/students'
    | '/app/school/teachers'
    | '/app/school/texts'
    | '/app/student/progresso'
    | '/app/student/simulados'
    | '/app/teacher/resultados'
    | '/app/teacher/rubricas'
    | '/app/teacher/tentativas'
    | '/app/admin/'
    | '/app/school/'
    | '/app/student/'
    | '/app/teacher/'
    | '/app/admin/schools/$id'
    | '/app/school/simulados/$id'
    | '/app/student/resultado/$attemptId'
    | '/app/student/simulado/$id'
    | '/app/admin/schools/'
    | '/app/school/simulados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/profile'
    | '/auth/student'
    | '/app'
    | '/auth'
    | '/app/admin/audit'
    | '/app/admin/finance'
    | '/app/admin/logs'
    | '/app/admin/monitoring'
    | '/app/admin/plans'
    | '/app/admin/reports'
    | '/app/admin/settings'
    | '/app/admin/subscriptions'
    | '/app/admin/users'
    | '/app/school/classes'
    | '/app/school/students'
    | '/app/school/teachers'
    | '/app/school/texts'
    | '/app/student/progresso'
    | '/app/student/simulados'
    | '/app/teacher/resultados'
    | '/app/teacher/rubricas'
    | '/app/teacher/tentativas'
    | '/app/admin'
    | '/app/school'
    | '/app/student'
    | '/app/teacher'
    | '/app/admin/schools/$id'
    | '/app/school/simulados/$id'
    | '/app/student/resultado/$attemptId'
    | '/app/student/simulado/$id'
    | '/app/admin/schools'
    | '/app/school/simulados'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/profile'
    | '/auth/student'
    | '/app/'
    | '/auth/'
    | '/app/admin/audit'
    | '/app/admin/finance'
    | '/app/admin/logs'
    | '/app/admin/monitoring'
    | '/app/admin/plans'
    | '/app/admin/reports'
    | '/app/admin/settings'
    | '/app/admin/subscriptions'
    | '/app/admin/users'
    | '/app/school/classes'
    | '/app/school/students'
    | '/app/school/teachers'
    | '/app/school/texts'
    | '/app/student/progresso'
    | '/app/student/simulados'
    | '/app/teacher/resultados'
    | '/app/teacher/rubricas'
    | '/app/teacher/tentativas'
    | '/app/admin/'
    | '/app/school/'
    | '/app/student/'
    | '/app/teacher/'
    | '/app/admin/schools/$id'
    | '/app/school/simulados/$id'
    | '/app/student/resultado/$attemptId'
    | '/app/student/simulado/$id'
    | '/app/admin/schools/'
    | '/app/school/simulados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthStudentRoute: typeof AuthStudentRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/student': {
      id: '/auth/student'
      path: '/auth/student'
      fullPath: '/auth/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/admin/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/finance': {
      id: '/app/admin/finance'
      path: '/admin/finance'
      fullPath: '/app/admin/finance'
      preLoaderRoute: typeof AppAdminFinanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/logs': {
      id: '/app/admin/logs'
      path: '/admin/logs'
      fullPath: '/app/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/monitoring': {
      id: '/app/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/app/admin/monitoring'
      preLoaderRoute: typeof AppAdminMonitoringRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/plans': {
      id: '/app/admin/plans'
      path: '/admin/plans'
      fullPath: '/app/admin/plans'
      preLoaderRoute: typeof AppAdminPlansRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/reports': {
      id: '/app/admin/reports'
      path: '/admin/reports'
      fullPath: '/app/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/admin/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/subscriptions': {
      id: '/app/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/app/admin/subscriptions'
      preLoaderRoute: typeof AppAdminSubscriptionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/school/': {
      id: '/app/school/'
      path: '/school'
      fullPath: '/app/school/'
      preLoaderRoute: typeof AppSchoolIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/school/classes': {
      id: '/app/school/classes'
      path: '/school/classes'
      fullPath: '/app/school/classes'
      preLoaderRoute: typeof AppSchoolClassesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/school/students': {
      id: '/app/school/students'
      path: '/school/students'
      fullPath: '/app/school/students'
      preLoaderRoute: typeof AppSchoolStudentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/school/teachers': {
      id: '/app/school/teachers'
      path: '/school/teachers'
      fullPath: '/app/school/teachers'
      preLoaderRoute: typeof AppSchoolTeachersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/school/texts': {
      id: '/app/school/texts'
      path: '/school/texts'
      fullPath: '/app/school/texts'
      preLoaderRoute: typeof AppSchoolTextsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/student/': {
      id: '/app/student/'
      path: '/student'
      fullPath: '/app/student/'
      preLoaderRoute: typeof AppStudentIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/student/progresso': {
      id: '/app/student/progresso'
      path: '/student/progresso'
      fullPath: '/app/student/progresso'
      preLoaderRoute: typeof AppStudentProgressoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/student/simulados': {
      id: '/app/student/simulados'
      path: '/student/simulados'
      fullPath: '/app/student/simulados'
      preLoaderRoute: typeof AppStudentSimuladosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/teacher/': {
      id: '/app/teacher/'
      path: '/teacher'
      fullPath: '/app/teacher/'
      preLoaderRoute: typeof AppTeacherIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/teacher/resultados': {
      id: '/app/teacher/resultados'
      path: '/teacher/resultados'
      fullPath: '/app/teacher/resultados'
      preLoaderRoute: typeof AppTeacherResultadosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/teacher/rubricas': {
      id: '/app/teacher/rubricas'
      path: '/teacher/rubricas'
      fullPath: '/app/teacher/rubricas'
      preLoaderRoute: typeof AppTeacherRubricasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/teacher/tentativas': {
      id: '/app/teacher/tentativas'
      path: '/teacher/tentativas'
      fullPath: '/app/teacher/tentativas'
      preLoaderRoute: typeof AppTeacherTentativasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/schools/': {
      id: '/app/admin/schools/'
      path: '/admin/schools'
      fullPath: '/app/admin/schools/'
      preLoaderRoute: typeof AppAdminSchoolsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/schools/$id': {
      id: '/app/admin/schools/$id'
      path: '/admin/schools/$id'
      fullPath: '/app/admin/schools/$id'
      preLoaderRoute: typeof AppAdminSchoolsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/school/simulados/': {
      id: '/app/school/simulados/'
      path: '/school/simulados'
      fullPath: '/app/school/simulados/'
      preLoaderRoute: typeof AppSchoolSimuladosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/school/simulados/$id': {
      id: '/app/school/simulados/$id'
      path: '/school/simulados/$id'
      fullPath: '/app/school/simulados/$id'
      preLoaderRoute: typeof AppSchoolSimuladosIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/student/resultado/$attemptId': {
      id: '/app/student/resultado/$attemptId'
      path: '/student/resultado/$attemptId'
      fullPath: '/app/student/resultado/$attemptId'
      preLoaderRoute: typeof AppStudentResultadoAttemptIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/student/simulado/$id': {
      id: '/app/student/simulado/$id'
      path: '/student/simulado/$id'
      fullPath: '/app/student/simulado/$id'
      preLoaderRoute: typeof AppStudentSimuladoIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminFinanceRoute: typeof AppAdminFinanceRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminMonitoringRoute: typeof AppAdminMonitoringRoute
  AppAdminPlansRoute: typeof AppAdminPlansRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminSubscriptionsRoute: typeof AppAdminSubscriptionsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppSchoolClassesRoute: typeof AppSchoolClassesRoute
  AppSchoolStudentsRoute: typeof AppSchoolStudentsRoute
  AppSchoolTeachersRoute: typeof AppSchoolTeachersRoute
  AppSchoolTextsRoute: typeof AppSchoolTextsRoute
  AppStudentProgressoRoute: typeof AppStudentProgressoRoute
  AppStudentSimuladosRoute: typeof AppStudentSimuladosRoute
  AppTeacherResultadosRoute: typeof AppTeacherResultadosRoute
  AppTeacherRubricasRoute: typeof AppTeacherRubricasRoute
  AppTeacherTentativasRoute: typeof AppTeacherTentativasRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppSchoolIndexRoute: typeof AppSchoolIndexRoute
  AppStudentIndexRoute: typeof AppStudentIndexRoute
  AppTeacherIndexRoute: typeof AppTeacherIndexRoute
  AppAdminSchoolsIdRoute: typeof AppAdminSchoolsIdRoute
  AppSchoolSimuladosIdRoute: typeof AppSchoolSimuladosIdRoute
  AppStudentResultadoAttemptIdRoute: typeof AppStudentResultadoAttemptIdRoute
  AppStudentSimuladoIdRoute: typeof AppStudentSimuladoIdRoute
  AppAdminSchoolsIndexRoute: typeof AppAdminSchoolsIndexRoute
  AppSchoolSimuladosIndexRoute: typeof AppSchoolSimuladosIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminFinanceRoute: AppAdminFinanceRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminMonitoringRoute: AppAdminMonitoringRoute,
  AppAdminPlansRoute: AppAdminPlansRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminSubscriptionsRoute: AppAdminSubscriptionsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppSchoolClassesRoute: AppSchoolClassesRoute,
  AppSchoolStudentsRoute: AppSchoolStudentsRoute,
  AppSchoolTeachersRoute: AppSchoolTeachersRoute,
  AppSchoolTextsRoute: AppSchoolTextsRoute,
  AppStudentProgressoRoute: AppStudentProgressoRoute,
  AppStudentSimuladosRoute: AppStudentSimuladosRoute,
  AppTeacherResultadosRoute: AppTeacherResultadosRoute,
  AppTeacherRubricasRoute: AppTeacherRubricasRoute,
  AppTeacherTentativasRoute: AppTeacherTentativasRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppSchoolIndexRoute: AppSchoolIndexRoute,
  AppStudentIndexRoute: AppStudentIndexRoute,
  AppTeacherIndexRoute: AppTeacherIndexRoute,
  AppAdminSchoolsIdRoute: AppAdminSchoolsIdRoute,
  AppSchoolSimuladosIdRoute: AppSchoolSimuladosIdRoute,
  AppStudentResultadoAttemptIdRoute: AppStudentResultadoAttemptIdRoute,
  AppStudentSimuladoIdRoute: AppStudentSimuladoIdRoute,
  AppAdminSchoolsIndexRoute: AppAdminSchoolsIndexRoute,
  AppSchoolSimuladosIndexRoute: AppSchoolSimuladosIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthStudentRoute: AuthStudentRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
