-- 0011 Row Level Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.schools ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.texts ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.simulados ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.simulado_pages ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.simulado_blocks ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.simulado_attempts ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.simulado_answers ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.student_credentials ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.simulado_retakes ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.question_keys ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;
